##
## EPITECH PROJECT, 2020
## makefile
## File description:
## makefile
##

CFLAGS = -Wall -Wextra -I include/

all:
	cd antman/ && make all
	cd giantman/ && make all

debug:
	cd antman/ && make debug
	cd giantman/ && make debug

clean:
	cd antman/ && make clean
	cd giantman/ && make clean

fclean:
	cd antman/ && make fclean
	cd giantman/ && make fclean

re:
	cd antman/ && make re
	cd giantman/ && make re

re_debug:
	cd antman/ && make re_debug
	cd giantman/ && make re_debug